name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: cargo test
  build_martix:
    strategy:
      matrix: 
        os: [macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-bundle
      uses: baptiste0928/cargo-install@v3.1.0
      with:
        crate: cargo-bundle
    - name: Run cargo bundle
      run: cargo bundle --release
    - name: Modify Info.plist
      run: |
        cd ./script
        cargo run
    - name: Upload
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Riri-${{ runner.os }}-${{ runner.arch }}
        path: target/release/bundle/osx
    

      
