name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: cargo test
    

  build-aarch:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-bundle
      uses: baptiste0928/cargo-install@v3.1.0
      with:
        crate: cargo-bundle
    - name: Run cargo bundle
      run: cargo bundle --release
    - name: Upload
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Riri-aarch
        path: target/release/bundle/osx

  build-x86-64:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-bundle
      uses: baptiste0928/cargo-install@v3.1.0
      with:
        crate: cargo-bundle
    - name: Run cargo bundle
      run: cargo bundle --release
    - name: Upload
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Riri-x86-64
        path: target/release/bundle/osx
      
